/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const Achievement = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'year' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Variant({
    'championship' : IDL.Null,
    'podium' : IDL.Null,
    'record' : IDL.Null,
  }),
});
export const Driver = IDL.Record({
  'id' : Id,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'nationality' : IDL.Text,
  'podiums' : IDL.Nat,
  'number' : IDL.Nat,
  'position' : IDL.Int,
});
export const Race = IDL.Record({
  'id' : Id,
  'status' : IDL.Variant({ 'upcoming' : IDL.Null, 'completed' : IDL.Null }),
  'date' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
  'circuit' : IDL.Text,
});
export const Sponsor = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'tier' : IDL.Variant({
    'title' : IDL.Null,
    'official' : IDL.Null,
    'partner' : IDL.Null,
  }),
  'website' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createAchievement' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Variant({
          'championship' : IDL.Null,
          'podium' : IDL.Null,
          'record' : IDL.Null,
        }),
      ],
      [Achievement],
      [],
    ),
  'createDriver' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Int, IDL.Text, IDL.Nat, IDL.Nat],
      [Driver],
      [],
    ),
  'createRace' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Race], []),
  'createSponsor' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'title' : IDL.Null,
          'official' : IDL.Null,
          'partner' : IDL.Null,
        }),
        IDL.Text,
      ],
      [Sponsor],
      [],
    ),
  'deleteAchievement' : IDL.Func([Id], [], []),
  'deleteDriver' : IDL.Func([Id], [], []),
  'deleteMessage' : IDL.Func([Id], [], []),
  'deleteRace' : IDL.Func([Id], [], []),
  'deleteSponsor' : IDL.Func([Id], [], []),
  'getAchievement' : IDL.Func([Id], [IDL.Opt(Achievement)], ['query']),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getDriver' : IDL.Func([Id], [IDL.Opt(Driver)], ['query']),
  'getDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getMessage' : IDL.Func([Id], [IDL.Opt(Message)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getRace' : IDL.Func([Id], [IDL.Opt(Race)], ['query']),
  'getRaces' : IDL.Func([], [IDL.Vec(Race)], ['query']),
  'getSponsor' : IDL.Func([Id], [IDL.Opt(Sponsor)], ['query']),
  'getSponsors' : IDL.Func([], [IDL.Vec(Sponsor)], ['query']),
  'initSeedData' : IDL.Func([], [], []),
  'reset' : IDL.Func([], [], []),
  'submitMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Message], []),
  'updateAchievement' : IDL.Func(
      [
        Id,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Variant({
          'championship' : IDL.Null,
          'podium' : IDL.Null,
          'record' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateDriver' : IDL.Func(
      [Id, IDL.Text, IDL.Nat, IDL.Text, IDL.Int, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateRace' : IDL.Func(
      [
        Id,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'upcoming' : IDL.Null, 'completed' : IDL.Null }),
      ],
      [],
      [],
    ),
  'updateSponsor' : IDL.Func(
      [
        Id,
        IDL.Text,
        IDL.Variant({
          'title' : IDL.Null,
          'official' : IDL.Null,
          'partner' : IDL.Null,
        }),
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const Achievement = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'year' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Variant({
      'championship' : IDL.Null,
      'podium' : IDL.Null,
      'record' : IDL.Null,
    }),
  });
  const Driver = IDL.Record({
    'id' : Id,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'nationality' : IDL.Text,
    'podiums' : IDL.Nat,
    'number' : IDL.Nat,
    'position' : IDL.Int,
  });
  const Race = IDL.Record({
    'id' : Id,
    'status' : IDL.Variant({ 'upcoming' : IDL.Null, 'completed' : IDL.Null }),
    'date' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
    'circuit' : IDL.Text,
  });
  const Sponsor = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'tier' : IDL.Variant({
      'title' : IDL.Null,
      'official' : IDL.Null,
      'partner' : IDL.Null,
    }),
    'website' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createAchievement' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Variant({
            'championship' : IDL.Null,
            'podium' : IDL.Null,
            'record' : IDL.Null,
          }),
        ],
        [Achievement],
        [],
      ),
    'createDriver' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Int, IDL.Text, IDL.Nat, IDL.Nat],
        [Driver],
        [],
      ),
    'createRace' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Race],
        [],
      ),
    'createSponsor' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'title' : IDL.Null,
            'official' : IDL.Null,
            'partner' : IDL.Null,
          }),
          IDL.Text,
        ],
        [Sponsor],
        [],
      ),
    'deleteAchievement' : IDL.Func([Id], [], []),
    'deleteDriver' : IDL.Func([Id], [], []),
    'deleteMessage' : IDL.Func([Id], [], []),
    'deleteRace' : IDL.Func([Id], [], []),
    'deleteSponsor' : IDL.Func([Id], [], []),
    'getAchievement' : IDL.Func([Id], [IDL.Opt(Achievement)], ['query']),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getDriver' : IDL.Func([Id], [IDL.Opt(Driver)], ['query']),
    'getDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getMessage' : IDL.Func([Id], [IDL.Opt(Message)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getRace' : IDL.Func([Id], [IDL.Opt(Race)], ['query']),
    'getRaces' : IDL.Func([], [IDL.Vec(Race)], ['query']),
    'getSponsor' : IDL.Func([Id], [IDL.Opt(Sponsor)], ['query']),
    'getSponsors' : IDL.Func([], [IDL.Vec(Sponsor)], ['query']),
    'initSeedData' : IDL.Func([], [], []),
    'reset' : IDL.Func([], [], []),
    'submitMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Message], []),
    'updateAchievement' : IDL.Func(
        [
          Id,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Variant({
            'championship' : IDL.Null,
            'podium' : IDL.Null,
            'record' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateDriver' : IDL.Func(
        [Id, IDL.Text, IDL.Nat, IDL.Text, IDL.Int, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateRace' : IDL.Func(
        [
          Id,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'upcoming' : IDL.Null, 'completed' : IDL.Null }),
        ],
        [],
        [],
      ),
    'updateSponsor' : IDL.Func(
        [
          Id,
          IDL.Text,
          IDL.Variant({
            'title' : IDL.Null,
            'official' : IDL.Null,
            'partner' : IDL.Null,
          }),
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };