/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : Id,
  'title' : string,
  'year' : bigint,
  'description' : string,
  'category' : { 'championship' : null } |
    { 'podium' : null } |
    { 'record' : null },
}
export interface Driver {
  'id' : Id,
  'bio' : string,
  'name' : string,
  'wins' : bigint,
  'nationality' : string,
  'podiums' : bigint,
  'number' : bigint,
  'position' : bigint,
}
export type Id = bigint;
export interface Message {
  'id' : Id,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Race {
  'id' : Id,
  'status' : { 'upcoming' : null } |
    { 'completed' : null },
  'date' : string,
  'name' : string,
  'location' : string,
  'circuit' : string,
}
export interface Sponsor {
  'id' : Id,
  'name' : string,
  'tier' : { 'title' : null } |
    { 'official' : null } |
    { 'partner' : null },
  'website' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'createAchievement' : ActorMethod<
    [
      string,
      bigint,
      string,
      { 'championship' : null } |
        { 'podium' : null } |
        { 'record' : null },
    ],
    Achievement
  >,
  'createDriver' : ActorMethod<
    [string, bigint, string, bigint, string, bigint, bigint],
    Driver
  >,
  'createRace' : ActorMethod<[string, string, string, string], Race>,
  'createSponsor' : ActorMethod<
    [
      string,
      { 'title' : null } |
        { 'official' : null } |
        { 'partner' : null },
      string,
    ],
    Sponsor
  >,
  'deleteAchievement' : ActorMethod<[Id], undefined>,
  'deleteDriver' : ActorMethod<[Id], undefined>,
  'deleteMessage' : ActorMethod<[Id], undefined>,
  'deleteRace' : ActorMethod<[Id], undefined>,
  'deleteSponsor' : ActorMethod<[Id], undefined>,
  'getAchievement' : ActorMethod<[Id], [] | [Achievement]>,
  'getAchievements' : ActorMethod<[], Array<Achievement>>,
  'getDriver' : ActorMethod<[Id], [] | [Driver]>,
  'getDrivers' : ActorMethod<[], Array<Driver>>,
  'getMessage' : ActorMethod<[Id], [] | [Message]>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getRace' : ActorMethod<[Id], [] | [Race]>,
  'getRaces' : ActorMethod<[], Array<Race>>,
  'getSponsor' : ActorMethod<[Id], [] | [Sponsor]>,
  'getSponsors' : ActorMethod<[], Array<Sponsor>>,
  'initSeedData' : ActorMethod<[], undefined>,
  'reset' : ActorMethod<[], undefined>,
  'submitMessage' : ActorMethod<[string, string, string], Message>,
  'updateAchievement' : ActorMethod<
    [
      Id,
      string,
      bigint,
      string,
      { 'championship' : null } |
        { 'podium' : null } |
        { 'record' : null },
    ],
    undefined
  >,
  'updateDriver' : ActorMethod<
    [Id, string, bigint, string, bigint, string, bigint, bigint],
    undefined
  >,
  'updateRace' : ActorMethod<
    [
      Id,
      string,
      string,
      string,
      string,
      { 'upcoming' : null } |
        { 'completed' : null },
    ],
    undefined
  >,
  'updateSponsor' : ActorMethod<
    [
      Id,
      string,
      { 'title' : null } |
        { 'official' : null } |
        { 'partner' : null },
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];