/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Driver {
    id: Id;
    bio: string;
    name: string;
    wins: bigint;
    nationality: string;
    podiums: bigint;
    number: bigint;
    position: bigint;
}
export interface Sponsor {
    id: Id;
    name: string;
    tier: Variant_title_official_partner;
    website: string;
}
export type Id = bigint;
export interface Message {
    id: Id;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface Race {
    id: Id;
    status: Variant_upcoming_completed;
    date: string;
    name: string;
    location: string;
    circuit: string;
}
export interface Achievement {
    id: Id;
    title: string;
    year: bigint;
    description: string;
    category: Variant_championship_podium_record;
}
export enum Variant_championship_podium_record {
    championship = "championship",
    podium = "podium",
    record = "record"
}
export enum Variant_title_official_partner {
    title = "title",
    official = "official",
    partner = "partner"
}
export enum Variant_upcoming_completed {
    upcoming = "upcoming",
    completed = "completed"
}
export interface backendInterface {
    createAchievement(title: string, year: bigint, description: string, category: Variant_championship_podium_record): Promise<Achievement>;
    createDriver(name: string, number: bigint, nationality: string, position: bigint, bio: string, wins: bigint, podiums: bigint): Promise<Driver>;
    createRace(name: string, location: string, date: string, circuit: string): Promise<Race>;
    createSponsor(name: string, tier: Variant_title_official_partner, website: string): Promise<Sponsor>;
    deleteAchievement(id: Id): Promise<void>;
    deleteDriver(id: Id): Promise<void>;
    deleteMessage(id: Id): Promise<void>;
    deleteRace(id: Id): Promise<void>;
    deleteSponsor(id: Id): Promise<void>;
    getAchievement(id: Id): Promise<Achievement | null>;
    getAchievements(): Promise<Array<Achievement>>;
    getDriver(id: Id): Promise<Driver | null>;
    getDrivers(): Promise<Array<Driver>>;
    getMessage(id: Id): Promise<Message | null>;
    getMessages(): Promise<Array<Message>>;
    getRace(id: Id): Promise<Race | null>;
    getRaces(): Promise<Array<Race>>;
    getSponsor(id: Id): Promise<Sponsor | null>;
    getSponsors(): Promise<Array<Sponsor>>;
    initSeedData(): Promise<void>;
    reset(): Promise<void>;
    submitMessage(name: string, email: string, message: string): Promise<Message>;
    updateAchievement(id: Id, title: string, year: bigint, description: string, category: Variant_championship_podium_record): Promise<void>;
    updateDriver(id: Id, name: string, number: bigint, nationality: string, position: bigint, bio: string, wins: bigint, podiums: bigint): Promise<void>;
    updateRace(id: Id, name: string, location: string, date: string, circuit: string, status: Variant_upcoming_completed): Promise<void>;
    updateSponsor(id: Id, name: string, tier: Variant_title_official_partner, website: string): Promise<void>;
}
import type { Achievement as _Achievement, Driver as _Driver, Id as _Id, Message as _Message, Race as _Race, Sponsor as _Sponsor } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAchievement(arg0: string, arg1: bigint, arg2: string, arg3: Variant_championship_podium_record): Promise<Achievement> {
        if (this.processError) {
            try {
                const result = await this.actor.createAchievement(arg0, arg1, arg2, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Achievement_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAchievement(arg0, arg1, arg2, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Achievement_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDriver(arg0: string, arg1: bigint, arg2: string, arg3: bigint, arg4: string, arg5: bigint, arg6: bigint): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.createDriver(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDriver(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createRace(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Race> {
        if (this.processError) {
            try {
                const result = await this.actor.createRace(arg0, arg1, arg2, arg3);
                return from_candid_Race_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRace(arg0, arg1, arg2, arg3);
            return from_candid_Race_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSponsor(arg0: string, arg1: Variant_title_official_partner, arg2: string): Promise<Sponsor> {
        if (this.processError) {
            try {
                const result = await this.actor.createSponsor(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Sponsor_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSponsor(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Sponsor_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAchievement(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAchievement(arg0);
            return result;
        }
    }
    async deleteDriver(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDriver(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async deleteRace(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRace(arg0);
            return result;
        }
    }
    async deleteSponsor(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSponsor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSponsor(arg0);
            return result;
        }
    }
    async getAchievement(arg0: Id): Promise<Achievement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievement(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievement(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriver(arg0: Id): Promise<Driver | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDrivers(): Promise<Array<Driver>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrivers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrivers();
            return result;
        }
    }
    async getMessage(arg0: Id): Promise<Message | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessage(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessage(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getRace(arg0: Id): Promise<Race | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRace(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRace(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRaces(): Promise<Array<Race>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRaces();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRaces();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSponsor(arg0: Id): Promise<Sponsor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSponsor(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSponsor(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSponsors(): Promise<Array<Sponsor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSponsors();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSponsors();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSeedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSeedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSeedData();
            return result;
        }
    }
    async reset(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reset();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reset();
            return result;
        }
    }
    async submitMessage(arg0: string, arg1: string, arg2: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAchievement(arg0: Id, arg1: string, arg2: bigint, arg3: string, arg4: Variant_championship_podium_record): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAchievement(arg0, arg1, arg2, arg3, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAchievement(arg0, arg1, arg2, arg3, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateDriver(arg0: Id, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: string, arg6: bigint, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriver(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriver(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateRace(arg0: Id, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Variant_upcoming_completed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRace(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n20(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRace(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n20(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateSponsor(arg0: Id, arg1: string, arg2: Variant_title_official_partner, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSponsor(arg0, arg1, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSponsor(arg0, arg1, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_Achievement_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Achievement {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Race_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Race): Race {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Sponsor_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sponsor): Sponsor {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Achievement]): Achievement | null {
    return value.length === 0 ? null : from_candid_Achievement_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Driver]): Driver | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Race]): Race | null {
    return value.length === 0 ? null : from_candid_Race_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sponsor]): Sponsor | null {
    return value.length === 0 ? null : from_candid_Sponsor_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    name: string;
    tier: {
        title: null;
    } | {
        official: null;
    } | {
        partner: null;
    };
    website: string;
}): {
    id: Id;
    name: string;
    tier: Variant_title_official_partner;
    website: string;
} {
    return {
        id: value.id,
        name: value.name,
        tier: from_candid_variant_n11(_uploadFile, _downloadFile, value.tier),
        website: value.website
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    year: bigint;
    description: string;
    category: {
        championship: null;
    } | {
        podium: null;
    } | {
        record: null;
    };
}): {
    id: Id;
    title: string;
    year: bigint;
    description: string;
    category: Variant_championship_podium_record;
} {
    return {
        id: value.id,
        title: value.title,
        year: value.year,
        description: value.description,
        category: from_candid_variant_n4(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: {
        upcoming: null;
    } | {
        completed: null;
    };
    date: string;
    name: string;
    location: string;
    circuit: string;
}): {
    id: Id;
    status: Variant_upcoming_completed;
    date: string;
    name: string;
    location: string;
    circuit: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n7(_uploadFile, _downloadFile, value.status),
        date: value.date,
        name: value.name,
        location: value.location,
        circuit: value.circuit
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: null;
} | {
    official: null;
} | {
    partner: null;
}): Variant_title_official_partner {
    return "title" in value ? Variant_title_official_partner.title : "official" in value ? Variant_title_official_partner.official : "partner" in value ? Variant_title_official_partner.partner : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    championship: null;
} | {
    podium: null;
} | {
    record: null;
}): Variant_championship_podium_record {
    return "championship" in value ? Variant_championship_podium_record.championship : "podium" in value ? Variant_championship_podium_record.podium : "record" in value ? Variant_championship_podium_record.record : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
}): Variant_upcoming_completed {
    return "upcoming" in value ? Variant_upcoming_completed.upcoming : "completed" in value ? Variant_upcoming_completed.completed : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Array<Achievement> {
    return value.map((x)=>from_candid_Achievement_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Race>): Array<Race> {
    return value.map((x)=>from_candid_Race_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sponsor>): Array<Sponsor> {
    return value.map((x)=>from_candid_Sponsor_n9(_uploadFile, _downloadFile, x));
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_championship_podium_record): {
    championship: null;
} | {
    podium: null;
} | {
    record: null;
} {
    return value == Variant_championship_podium_record.championship ? {
        championship: null
    } : value == Variant_championship_podium_record.podium ? {
        podium: null
    } : value == Variant_championship_podium_record.record ? {
        record: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_upcoming_completed): {
    upcoming: null;
} | {
    completed: null;
} {
    return value == Variant_upcoming_completed.upcoming ? {
        upcoming: null
    } : value == Variant_upcoming_completed.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_title_official_partner): {
    title: null;
} | {
    official: null;
} | {
    partner: null;
} {
    return value == Variant_title_official_partner.title ? {
        title: null
    } : value == Variant_title_official_partner.official ? {
        official: null
    } : value == Variant_title_official_partner.partner ? {
        partner: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
